# Generated by Django 3.0.4 on 2020-04-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
