# Generated by Django 3.0.4 on 2020-04-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200405_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
