# Generated by Django 3.0.4 on 2020-04-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
