# Generated by Django 3.0.4 on 2020-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('token', models.CharField(blank=True, max_length=70, unique=True, verbose_name='Токен')),
            ],
        ),
    ]
